http:
  middlewares:
    # Middleware de seguridad b치sico - Headers de seguridad HTTP
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    # Middleware de compresi칩n - Mejora rendimiento
    default-compress:
      compress: {}

    # Rate limiting b치sico - Protecci칩n contra abuso
    rate-limit:
      rateLimit:
        burst: 100
        average: 50
