networks:
  proxy:
    external: true

services:

  hello-world:
    image: nginx:alpine
    container_name: hello-world
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    user: ${PUID}:${PGID}
    labels:
      traefik.enable: true
      traefik.http.routers.test.rule: "Host(`test.${BASE_DOMAIN}`)"
      traefik.http.routers.test.tls: "true"
      traefik.http.routers.test.tls.certresolver: "cloudflare"
      traefik.http.services.test.loadbalancer.server.port: "80"
