#!/bin/bash
# Detects the host's physical disks and generates docker-compose.override.yml
# so beszel-agent can read S.M.A.R.T. data without bind-mounting the full
# host /dev (which breaks the container's own /dev/pts — see moby/moby#19464).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OVERRIDE_FILE="${SCRIPT_DIR}/docker-compose.override.yml"

# Reads host /sys/block from a throwaway container (the HMS container itself
# has no /dev or /sys mounted, only docker.sock) to list whole-disk devices,
# excluding loopback/ram/device-mapper/optical/zram, and collapsing NVMe
# namespaces (nvme0n1) down to their controller name (nvme0), which is what
# smartctl expects.
disks="$(
  docker run --rm -v /sys:/sys:ro alpine:latest ls -1 /sys/block 2>/dev/null \
    | grep -Ev '^(loop|ram|dm-|sr|zram)' \
    | sed -E 's/^(nvme[0-9]+)n[0-9]+$/\1/' \
    | sort -u
)"

if [ -z "${disks}" ]; then
  echo "No physical disks detected; skipping beszel-agent SMART device mapping."
  rm -f "${OVERRIDE_FILE}"
  exit 0
fi

{
  echo "# Auto-generated by pre-deploy.sh on every 'hms infra up' — do not edit, do not commit."
  echo "services:"
  echo "  beszel-agent:"
  echo "    devices:"
  while IFS= read -r disk; do
    echo "      - /dev/${disk}:/dev/${disk}"
  done <<< "${disks}"
} > "${OVERRIDE_FILE}"

echo "beszel-agent SMART devices detected: $(echo "${disks}" | tr '\n' ' ')"
