name: ${STACK_PREFIX}

x-hms:
  description: "Servidor de juego Core Keeper"

services:
  corekeeper:
    container_name: ${STACK_PREFIX}
    image: escaping/core-keeper-dedicated:latest
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WORLD_NAME=${WORLD_NAME}
      - GAME_ID=${GAME_ID}
      - SERVER_PASSWORD=${PASSWORD}
      - ACTIVATE_ALL_CONTENT=true
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      # Comentado para forzar que al iniciar el contenedor se descargue la última versión del servidor de Core Keeper,
      # ya que el repositorio oficial no se actualiza con cada nueva versión del juego.
      # - ${STACK_DATA}/server-files:/home/steam/core-keeper-dedicated
      - ${STACK_DATA}/server-data:/home/steam/core-keeper-data
    labels:
      - "hms.description=🎮 Servidor de juego Core Keeper"
