# Stack Steam - ArchiSteamFarm
# ==============================
# Farmeo y venta automática de cromos de Steam

config_files: []

services:
  asf:
    subdomain: "asf"
    protected: true

backups:
  exclude:
    - config/ASF/logs/
    - config/ASF/cache/

