name: ${STACK_PREFIX}

x-hms:
  description: "Servidor de juego Terraria con tShock (Oficial)"

services:
  terraria:
    container_name: ${STACK_PREFIX}
    image: ghcr.io/pryaxis/tshock:nuget-release
    restart: unless-stopped
    ports:
      - "7777:7777/tcp"
    environment:
      - TZ=${TZ}
      - TSHOCK_WORLD=${WORLD_NAME}
      - TSHOCK_WORLDSIZE=${WORLD_SIZE}
      - TSHOCK_DIFFICULTY=${DIFFICULTY}
      - TSHOCK_MOTD=${MOTD}
      - TSHOCK_SECURE=${SECURE}
      - TSHOCK_LANGUAGE=${LANGUAGE}
      - TSHOCK_MAXPLAYERS=${MAX_PLAYERS}
      - TSHOCK_AUTOCREATE=1
    volumes:
      - ${STACK_DATA}/worlds:/worlds
      - ${STACK_DATA}/config:/tshock
      - ${STACK_DATA}/plugins:/plugins
    command: ["-world","/worlds/my_world.wld","-autocreate","1"]
    labels:
      - "hms.description=🎮 Servidor de juego Terraria con tShock"
