name: ${STACK_PREFIX}

x-hms:
  description: "Servidor de juego Terraria con tModLoader"

services:
  terraria:
    container_name: ${STACK_PREFIX}
    image: hexlo/terraria-tmodloader-server:latest
    restart: unless-stopped
    ports:
      - "7777:7777/tcp"
    environment:
      - TZ=${TZ}
      - UID=${PUID}
      - GID=${PGID}
      - WORLD_NAME=${WORLD_NAME}
      - AUTOCREATE=${WORLD_SIZE}
      - DIFFICULTY=${DIFFICULTY}
      - MOTD=${MOTD}
      - WORLD="/home/tml/.local/share/Terraria/tModLoader/Worlds/world.wld"
      - LANGUAGE=${LANGUAGE}
      - MAXPLAYERS=${MAX_PLAYERS}
      - PASSWORD=${PASSWORD}
      - SECURE=${SECURE}
      - NPCSTREAM=${NPCSTREAM}
    volumes:
      - ${STACK_DATA}/Worlds:/home/tml/.local/share/Terraria/tModLoader/Worlds
      - ${STACK_DATA}/Mods:/home/tml/.local/share/Terraria/tModLoader/Mods
      - ${STACK_DATA}/ModConfigs:/home/tml/.local/share/Terraria/TModLoader/ModConfigs
    labels:
      - "hms.description=🎮 Servidor de juego Terraria con tModLoader (soporte para mods)"
