name: ${STACK_PREFIX}

x-hms:
  description: "Servidor de juego V Rising"

services:
  vrising:
    container_name: ${STACK_PREFIX}
    image: trueosiris/vrising
    restart: unless-stopped
    stop_grace_period: 2m
    # Required: https://github.com/TrueOsiris/docker-vrising#image-2026-02-21
    entrypoint: ["/bin/bash", "-c", "sed -i 's/\\r//g' /start.sh && exec /bin/bash /start.sh"]
    ports:
      - "${GAMEPORT}:${GAMEPORT}/udp"
      - "${QUERYPORT}:${QUERYPORT}/udp"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - SERVERNAME=${SERVER_NAME}
      - WORLDNAME=${WORLD_NAME}
      - GAMEPORT=${GAMEPORT}
      - QUERYPORT=${QUERYPORT}
      - HOST_SETTINGS_Password=${PASSWORD}
      - HOST_SETTINGS_ListOnSteam=${LIST_ON_STEAM}
      - HOST_SETTINGS_ListOnEOS=${LIST_ON_EOS}
      - GAME_SETTINGS_GameModeType=${GAME_MODE}
    volumes:
      - ${STACK_DATA}/server:/mnt/vrising/server
      - ${STACK_DATA}/persistentdata:/mnt/vrising/persistentdata
    labels:
      - "hms.description=🧛 Servidor de juego V Rising"
