name: home-server
services:
  cli:
    build:
      context: ../..
      dockerfile: docker/hms/Dockerfile
    container_name: hms
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    group_add:
      - "0"  # Agregar al grupo root para acceso al docker.sock
    volumes:
      - ../../config:/app/config:ro
      - ../../docker:/app/docker
      - ../../data:/app/data
      - ../../logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "false"
